apiVersion: v1
kind: Secret
metadata:
  name: storage-exporter-secret
  namespace: hspc-monitoring-system
type: Opaque
stringData:
  storage-exporter.yaml: |-
    storages:
    - serial: 54321
      url: http://172.16.1.1
      user: MaintenanceUser
      password: Password
