{
 "title": "HSPC Volumes",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(spc_volume_total_capacity, namespace)"
   },
   {
    "name": "persistentvolumeclaim",
    "label": "Persistent Volume Claim",
    "query": "label_values(spc_volume_total_capacity, persistentvolumeclaim)"
   },
   {
    "name": "storageclass",
    "label": "Storage Class",
    "query": "label_values({__name__=~\"spc_sc_pool_total_capacity|spc_volume_total_capacity\"}, storageclass)"
   },
   {
    "name": "serial_id",
    "label": "StorageSerialNumber",
    "query": "label_values({__name__=~\"spc_sc_pool_total_capacity|spc_volume_total_capacity\"}, serial_id)"
   },
   {
    "name": "pool_id",
    "label": "StoragePoolID",
    "query": "label_values({__name__=~\"spc_sc_pool_total_capacity|spc_volume_total_capacity\"},pool_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Used Capacity Rate of Volume (Top 10)",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(10, spc_volume_used_capacity_rate{persistentvolumeclaim=~\"${persistentvolumeclaim}\", storageclass=~\"${storageclass}\", namespace=~\"${namespace}\", serial_id=~\"${serial_id}\", pool_id=~\"${pool_id}\"})",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}} (LDEV: {{ldev_id_hex}}, StorageS/N: {{serial_id}})"
    }
   ]
  },
  {
   "title": "Used Capacity Rate of Pool (Top 3)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(3, spc_sc_pool_used_capacity_rate{storageclass=~\"${storageclass}\", serial_id=~\"${serial_id}\", pool_id=~\"${pool_id}\"})",
     "legendFormat": "{{storageclass}} (PoolID:{{pool_id}}, StorageS/N: {{serial_id}})"
    }
   ]
  },
  {
   "title": "Volumes managerd by HSPC",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(spc_volume_total_capacity{persistentvolumeclaim=~\"${persistentvolumeclaim}\", storageclass=~\"${storageclass}\", namespace=~\"${namespace}\", serial_id=~\"${serial_id}\", pool_id=~\"${pool_id}\"})"
    }
   ]
  },
  {
   "title": "HSPC Storage Classes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(spc_sc_pool_total_capacity{storageclass=~\"${storageclass}\", serial_id=~\"${serial_id}\", pool_id=~\"${pool_id}\"})"
    }
   ]
  },
  {
   "title": "Average Response Time of Read",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "spc_volume_average_read_response_time{persistentvolumeclaim=~\"${persistentvolumeclaim}\", storageclass=~\"${storageclass}\", namespace=~\"${namespace}\", serial_id=~\"${serial_id}\", pool_id=~\"${pool_id}\"}",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}} (LDEV: {{ldev_id_hex}}, StorageS/N: {{serial_id}})"
    }
   ]
  },
  {
   "title": "Total Read IOPS of volume",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spc_volume_total_read_iops{persistentvolumeclaim=~\"${persistentvolumeclaim}\", storageclass=~\"${storageclass}\", namespace=~\"${namespace}\", serial_id=~\"${serial_id}\", pool_id=~\"${pool_id}\"}",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}} (LDEV: {{ldev_id_hex}}, StorageS/N: {{serial_id}})"
    }
   ]
  },
  {
   "title": "Read Transfer Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "spc_volume_total_read_transfer_rate{persistentvolumeclaim=~\"${persistentvolumeclaim}\", storageclass=~\"${storageclass}\", namespace=~\"${namespace}\", serial_id=~\"${serial_id}\", pool_id=~\"${pool_id}\"}",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}} (LDEV: {{ldev_id_hex}}, StorageS/N: {{serial_id}})"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "spc_volume_read_cache_hit_rate{persistentvolumeclaim=~\"${persistentvolumeclaim}\", storageclass=~\"${storageclass}\", namespace=~\"${namespace}\", serial_id=~\"${serial_id}\", pool_id=~\"${pool_id}\"}",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}} (LDEV: {{ldev_id_hex}}, StorageS/N: {{serial_id}})"
    }
   ]
  },
  {
   "title": "Average Response Time of Write",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "spc_volume_average_write_response_time{persistentvolumeclaim=~\"${persistentvolumeclaim}\", storageclass=~\"${storageclass}\", namespace=~\"${namespace}\", serial_id=~\"${serial_id}\", pool_id=~\"${pool_id}\"}",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}} (LDEV: {{ldev_id_hex}}, StorageS/N: {{serial_id}})"
    }
   ]
  },
  {
   "title": "Total Write IOPS of volume",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spc_volume_total_write_iops{persistentvolumeclaim=~\"${persistentvolumeclaim}\", storageclass=~\"${storageclass}\", namespace=~\"${namespace}\", serial_id=~\"${serial_id}\", pool_id=~\"${pool_id}\"}",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}} (LDEV: {{ldev_id_hex}}, StorageS/N: {{serial_id}})"
    }
   ]
  },
  {
   "title": "Write Transfer Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "spc_volume_total_write_transfer_rate{persistentvolumeclaim=~\"${persistentvolumeclaim}\", storageclass=~\"${storageclass}\", namespace=~\"${namespace}\", serial_id=~\"${serial_id}\", pool_id=~\"${pool_id}\"}",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}} (LDEV: {{ldev_id_hex}}, StorageS/N: {{serial_id}})"
    }
   ]
  }
 ]
}