apiVersion: v1
kind: Pod
metadata:
  name: pod-sample
spec:
  containers:
    - name: my-busybox
      image: busybox
      volumeMounts:
        - mountPath: "/data"
          name: sample-volume
      command: ["sleep", "1000000"]
      imagePullPolicy: IfNotPresent
  volumes:
    - name: sample-volume
      persistentVolumeClaim:
        claimName: pvc-sample
