defaults {
    polling_interval     10
    recheck_wwid         yes
    find_multipaths      yes
    user_friendly_names  yes
    flush_on_last_del    yes
}
blacklist {
}
devices {
    device {
        vendor                 "HITACHI"
        product                "OPEN-.*"
        path_grouping_policy   "multibus"
        path_selector          "round-robin 0"
        path_checker           "tur"
        features               "0"
        hardware_handler       "0"
        failback               "immediate"
        rr_weight              "priorities"
        no_path_retry          fail
        fast_io_fail_tmo       5
        dev_loss_tmo           30
        eh_deadline            10
    }
}