apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-from-pvc-sample
spec:
  dataSource:
    name: pvc-sample
    kind: PersistentVolumeClaim
    apiGroup: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: sc-sample
