apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: snapshotclass-sample
driver: hspc.csi.hitachi.com
deletionPolicy: Delete
parameters:
  poolID: "1"
  csi.storage.k8s.io/snapshotter-secret-name: "secret-sample"
  csi.storage.k8s.io/snapshotter-secret-namespace: "default"
