apiVersion: v1
kind: Secret
metadata:
  name: hspc-replication-operator-storage-secrets
  namespace: hspc-replication-operator-system
type: Opaque
stringData:
  storage-secrets.yaml: |-
    storages:
    - serial: 54321 
      url: http://172.16.1.1
      user: UserPrimary 
      password: PasswordPrimary 
      journal: 1
    - serial: 400100
      url: http://172.16.1.2
      user: UserSecondary 
      password: PasswordSecondary
      journal: 2
